version: "2.2"
services:
  postgres:
    image: debezium/example-postgres:2.3.0.Final
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-startup-scripts/postgres/01_create_sample_data.sql:/docker-entrypoint-initdb.d/z01_create_sample_data.sql
    