version: "2.2"
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle
    environment:
      - ORACLE_PWD=Admin123
    ports:
      - 1521:1521
    volumes:
      - $PWD/db-startup-scripts/oracle:/opt/oracle/scripts/startup